[tool.poetry]
name = "aioli-client"
version = "0.1.0"
description = "REST API Client"
authors = ["Guillaume Gauvrit <guillaume@gauvr.it>"]
license = "BSD-derived"
packages = [
    { include = "aioli", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.7"
httpx = "^0.20.0"
pydantic = "^1.8.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytest-asyncio = "^0.16.0"
black = "^21.9b0"
isort = "^5.9.3"
Sphinx = "^4.2.0"
sphinx-rtd-theme = "^1.0.0"
fastapi = "^0.70.0"
uvicorn = "^0.15.0"

[tool.pytest.ini_options]
norecursedirs="tests/unittests/scanned_resources"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
